data:
  filepaths:
  - "data/ndbc/42003.csv"
  - "data/ndbc/41008.csv"
  - "data/ndbc/41010.csv"
  - "data/ndbc/44007.csv"
  - "data/ndbc/51003.csv"
  prediction_lengths: [1,3,6,12,24,36,48,60,72,84,96,108,120]

context-length: 512

training:
  train_size: 0.70
  val_size: 0.15
  test_size: 0.15
